In [2]:
import pandas as pd
df=pd.read_csv("Amazon Sale Report.csv" , low_memory=False)

In [3]:
df.shape

(128975, 24)

In [4]:
df.columns
df.dtypes

index                   int64
Order ID                  str
Date                      str
Status                    str
Fulfilment                str
Sales Channel             str
ship-service-level        str
Style                     str
SKU                       str
Category                  str
Size                      str
ASIN                      str
Courier Status            str
Qty                     int64
currency                  str
Amount                float64
ship-city                 str
ship-state                str
ship-postal-code      float64
ship-country              str
promotion-ids             str
B2B                      bool
fulfilled-by              str
Unnamed: 22            object
dtype: object

In [5]:
df.describe

<bound method NDFrame.describe of          index             Order ID      Date                        Status  \
0            0  405-8078784-5731545  04-30-22                     Cancelled
1            1  171-9198151-1101146  04-30-22  Shipped - Delivered to Buyer
2            2  404-0687676-7273146  04-30-22                       Shipped
3            3  403-9615377-8133951  04-30-22                     Cancelled
4            4  407-1069790-7240320  04-30-22                       Shipped
...        ...                  ...       ...                           ...
128970  128970  406-6001380-7673107  05-31-22                       Shipped
128971  128971  402-9551604-7544318  05-31-22                       Shipped
128972  128972  407-9547469-3152358  05-31-22                       Shipped
128973  128973  402-6184140-0545956  05-31-22                       Shipped
128974  128974  408-7436540-8728312  05-31-22                       Shipped

       Fulfilment Sales Channel  ship-service-level    Style              SKU  \
0        Merchant      Amazon.in           Standard   SET389   SET389-KR-NP-S
1        Merchant      Amazon.in           Standard  JNE3781  JNE3781-KR-XXXL
2          Amazon      Amazon.in          Expedited  JNE3371    JNE3371-KR-XL
3        Merchant      Amazon.in           Standard    J0341       J0341-DR-L
4          Amazon      Amazon.in          Expedited  JNE3671  JNE3671-TU-XXXL
...           ...            ...                ...      ...              ...
128970     Amazon      Amazon.in          Expedited  JNE3697    JNE3697-KR-XL
128971     Amazon      Amazon.in          Expedited   SET401   SET401-KR-NP-M
128972     Amazon      Amazon.in          Expedited    J0157     J0157-DR-XXL
128973     Amazon      Amazon.in          Expedited    J0012     J0012-SKD-XS
128974     Amazon      Amazon.in          Expedited    J0003      J0003-SET-S

             Category  ... currency   Amount    ship-city    ship-state  \
0                 Set  ...      INR   647.62       MUMBAI   MAHARASHTRA
1               kurta  ...      INR   406.00    BENGALURU     KARNATAKA
2               kurta  ...      INR   329.00  NAVI MUMBAI   MAHARASHTRA
3       Western Dress  ...      INR   753.33   PUDUCHERRY    PUDUCHERRY
4                 Top  ...      INR   574.00      CHENNAI    TAMIL NADU
...               ...  ...      ...      ...          ...           ...
128970          kurta  ...      INR   517.00    HYDERABAD     TELANGANA
128971            Set  ...      INR   999.00     GURUGRAM       HARYANA
128972  Western Dress  ...      INR   690.00    HYDERABAD     TELANGANA
128973            Set  ...      INR  1199.00        Halol       Gujarat
128974            Set  ...      INR   696.00       Raipur  CHHATTISGARH

       ship-postal-code  ship-country  \
0              400081.0            IN
1              560085.0            IN
2              410210.0            IN
3              605008.0            IN
4              600073.0            IN
...                 ...           ...
128970         500013.0            IN
128971         122004.0            IN
128972         500049.0            IN
128973         389350.0            IN
128974         492014.0            IN

                                            promotion-ids    B2B  \
0                                                     NaN  False
1       Amazon PLCC Free-Financing Universal Merchant ...  False
2            IN Core Free Shipping 2015/04/08 23-48-5-108   True
3                                                     NaN  False
4                                                     NaN  False
...                                                   ...    ...
128970                                                NaN  False
128971       IN Core Free Shipping 2015/04/08 23-48-5-108  False
128972                                                NaN  False
128973       IN Core Free Shipping 2015/04/08 23-48-5-108  False
128974       IN Core Free Shipping 2015/04/08 23-48-5-108  False

        fulfilled-by Unnamed: 22
0          Easy Ship         NaN
1          Easy Ship         NaN
2                NaN         NaN
3          Easy Ship         NaN
4                NaN         NaN
...              ...         ...
128970           NaN       False
128971           NaN       False
128972           NaN       False
128973           NaN       False
128974           NaN       False

[128975 rows x 24 columns]>

In [6]:
df.head()

,index,Order ID,Date,Status,Fulfilment,Sales Channel,ship-service-level,Style,SKU,Category,...,currency,Amount,ship-city,ship-state,ship-postal-code,ship-country,promotion-ids,B2B,fulfilled-by,Unnamed: 22
0,0,405-8078784-5731545,04-30-22,Cancelled,Merchant,Amazon.in,Standard,SET389,SET389-KR-NP-S,Set,...,INR,647.62,MUMBAI,MAHARASHTRA,400081.0,IN,NaN,False,Easy Ship,NaN
1,1,171-9198151-1101146,04-30-22,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,JNE3781,JNE3781-KR-XXXL,kurta,...,INR,406.00,BENGALURU,KARNATAKA,560085.0,IN,Amazon PLCC Free-Financing Universal Merchant ...,False,Easy Ship,NaN
2,2,404-0687676-7273146,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3371,JNE3371-KR-XL,kurta,...,INR,329.00,NAVI MUMBAI,MAHARASHTRA,410210.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,True,NaN,NaN
3,3,403-9615377-8133951,04-30-22,Cancelled,Merchant,Amazon.in,Standard,J0341,J0341-DR-L,Western Dress,...,INR,753.33,PUDUCHERRY,PUDUCHERRY,605008.0,IN,NaN,False,Easy Ship,NaN
4,4,407-1069790-7240320,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3671,JNE3671-TU-XXXL,Top,...,INR,574.00,CHENNAI,TAMIL NADU,600073.0,IN,NaN,False,NaN,NaN

In [7]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.drop_duplicates()

In [9]:
df.isnull().sum()

index                     0
Order ID                  0
Date                      0
Status                    0
Fulfilment                0
Sales Channel             0
ship-service-level        0
Style                     0
SKU                       0
Category                  0
Size                      0
ASIN                      0
Courier Status         6872
Qty                       0
currency               7795
Amount                 7795
ship-city                33
ship-state               33
ship-postal-code         33
ship-country             33
promotion-ids         49153
B2B                       0
fulfilled-by          89698
Unnamed: 22           49050
dtype: int64

In [10]:
df.drop(columns=['Unnamed: 22'], inplace=True)

In [11]:
df.sample(20)

,index,Order ID,Date,Status,Fulfilment,Sales Channel,ship-service-level,Style,SKU,Category,...,Qty,currency,Amount,ship-city,ship-state,ship-postal-code,ship-country,promotion-ids,B2B,fulfilled-by
116574,116574,407-5492940-7389954,06-09-22,Cancelled,Amazon,Amazon.in,Expedited,JNE1525,JNE1525-KR-UDF19BLACK-L,kurta,...,0,NaN,NaN,BENGALURU,KARNATAKA,560043.0,IN,NaN,False,NaN
31691,31691,404-1713962-4756362,04-11-22,Shipped,Amazon,Amazon.in,Expedited,SET331,SET331-KR-NP-XL,Set,...,1,INR,635.0,JALPAIGURI,WEST BENGAL,734008.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN
105625,105625,408-0229192-0320355,06-17-22,Cancelled,Merchant,Amazon.in,Standard,J0118,J0118-TP-XXL,Top,...,0,NaN,NaN,KOLKATA,WEST BENGAL,700074.0,IN,NaN,False,Easy Ship
63349,63349,404-8167437-2596330,05-20-22,Shipped,Amazon,Amazon.in,Expedited,J0339,J0339-DR-XL,Western Dress,...,1,INR,825.0,SOUTH GOA,GOA,403713.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN
121678,121678,407-2968389-7495546,06-06-22,Shipped,Amazon,Amazon.in,Expedited,J0285,J0285-SKD-M,Set,...,1,INR,1442.0,VADALI,Gujarat,383235.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN
7827,7827,407-2739881-9645957,04-25-22,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,J0009,J0009-SKD-XXXL,Set,...,1,INR,999.0,VADAKARA,KERALA,673101.0,IN,Amazon PLCC Free-Financing Universal Merchant ...,False,Easy Ship
77596,77596,403-2032027-4157944,05-08-22,Shipped - Returned to Seller,Merchant,Amazon.in,Standard,J0095,J0095-SET-M,Set,...,1,INR,643.0,EAST DELHI,DELHI,110051.0,IN,Amazon PLCC Free-Financing Universal Merchant ...,False,Easy Ship
16656,16656,405-7680918-9177148,04-20-22,Shipped,Amazon,Amazon.in,Expedited,J0341,J0341-DR-L,Western Dress,...,1,INR,744.0,BENGALURU,KARNATAKA,560037.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN
126503,126503,402-4812867-4481124,06-02-22,Shipped,Amazon,Amazon.in,Expedited,J0248,J0248-KR-DPT-XXXL,Set,...,1,INR,854.0,BENGALURU,KARNATAKA,560064.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN
7342,7342,402-9102454-0757903,04-26-22,Shipped,Amazon,Amazon.in,Expedited,JNE3405,JNE3405-KR-XXXL,kurta,...,1,INR,399.0,BENGALURU,KARNATAKA,560067.0,IN,NaN,False,NaN
66880,66880,404-4036690-3395531,05-17-22,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,JNE3905,JNE3905-DR-L,Western Dress,...,1,INR,625.0,DHARUHERA,HARYANA,123106.0,IN,Amazon PLCC Free-Financing Universal Merchant ...,False,Easy Ship
37263,37263,405-3325406-2557917,04-08-22,Shipped,Amazon,Amazon.in,Expedited,JNE3399,JNE3399-KR-M,kurta,...,1,INR,435.0,Ahmedabad,Gujarat,382449.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN
18984,18984,404-4527749-4337126,04-19-22,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,JNE3721,JNE3721-KR-XL,kurta,...,1,INR,329.0,THALASSERY,KERALA,670103.0,IN,Amazon PLCC Free-Financing Universal Merchant ...,False,Easy Ship
6978,6978,408-9977585-7668369,04-26-22,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,SET393,SET393-KR-NP-XL,Set,...,1,INR,969.0,NEDUVA,KERALA,676303.0,IN,Amazon PLCC Free-Financing Universal Merchant ...,False,Easy Ship
74466,74466,408-7961961-4916342,05-11-22,Shipped,Amazon,Amazon.in,Expedited,SET348,SET348-KR-NP-M,Set,...,1,INR,899.0,PUNE,MAHARASHTRA,411042.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN
58654,58654,407-8613444-1158716,05-24-22,Shipped,Amazon,Amazon.in,Expedited,MEN5009,MEN5009-KR-XXL,kurta,...,1,INR,709.0,BENGALURU,KARNATAKA,560077.0,IN,NaN,False,NaN
90757,90757,403-6477209-1240334,05-01-22,Shipped,Amazon,Amazon.in,Expedited,JNE3399,JNE3399-KR-XL,kurta,...,1,INR,435.0,BENGALURU,KARNATAKA,560098.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN
56512,56512,405-8746296-1888342,05-26-22,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,JNE3371,JNE3371-KR-S,kurta,...,1,INR,353.0,NEW DELHI,DELHI,110032.0,IN,Amazon PLCC Free-Financing Universal Merchant ...,False,Easy Ship
128897,128897,171-5413814-8866751,05-31-22,Shipped,Amazon,Amazon.in,Expedited,NW004,NW004-TP-PJ-XXXL,Set,...,1,INR,475.0,KANCHIPURAM,TAMIL NADU,600091.0,IN,NaN,False,NaN
92159,92159,171-1011723-6929945,06-28-22,Cancelled,Amazon,Amazon.in,Expedited,JNE3722,JNE3722-KR-S,kurta,...,0,NaN,NaN,CHOUBEPUR KALAN,UTTAR PRADESH,209203.0,IN,NaN,False,NaN

In [12]:
print(df['ship-state'].value_counts())

ship-state
MAHARASHTRA      22260
KARNATAKA        17326
TAMIL NADU       11483
TELANGANA        11330
UTTAR PRADESH    10638
                 ...
Nagaland             1
bihar                1
Mizoram              1
rajsthan             1
Rajsthan             1
Name: count, Length: 69, dtype: int64

In [13]:
df['ship-state'] = df['ship-state'].str.upper().str.strip()

In [14]:
print(df['ship-state'].value_counts())
print(df['ship-state'].nunique())

ship-state
MAHARASHTRA               22260
KARNATAKA                 17326
TAMIL NADU                11483
TELANGANA                 11330
UTTAR PRADESH             10638
DELHI                      6967
KERALA                     6585
WEST BENGAL                5963
ANDHRA PRADESH             5430
GUJARAT                    4489
HARYANA                    4415
RAJASTHAN                  2711
MADHYA PRADESH             2529
ODISHA                     2136
BIHAR                      2114
PUNJAB                     1917
ASSAM                      1663
UTTARAKHAND                1553
JHARKHAND                  1456
GOA                        1137
CHHATTISGARH                909
HIMACHAL PRADESH            788
JAMMU & KASHMIR             702
PUDUCHERRY                  350
CHANDIGARH                  333
MANIPUR                     316
ANDAMAN & NICOBAR           257
MEGHALAYA                   207
SIKKIM                      205
NAGALAND                    185
TRIPURA                     151
ARUNACHAL PRADESH           146
NEW DELHI                    81
MIZORAM                      76
DADRA AND NAGAR              70
LADAKH                       43
LAKSHADWEEP                   4
RAJSHTHAN                     3
ORISSA                        3
NL                            2
RJ                            2
RAJSTHAN                      2
PUNJAB/MOHALI/ZIRAKPUR        1
PB                            1
APO                           1
AR                            1
PONDICHERRY                   1
Name: count, dtype: int64
47

In [15]:
state_corrections = {
    'RAJSHTHAN': 'RAJASTHAN',
    'RAJSTHAN': 'RAJASTHAN',
    'ORISSA': 'ODISHA',
    'PB': 'PUNJAB',
    'RJ': 'RAJASTHAN',
    'NL': 'NAGALAND',
    'AR': 'ARUNACHAL PRADESH',
    'NEW DELHI': 'DELHI',
}

df['ship-state'] = df['ship-state'].replace(state_corrections)

# نمسح الصفوف اللي فيها قيم مش ولايات حقيقية أصلاً
df = df[~df['ship-state'].isin(['APO', 'PUNJAB/MOHALI/ZIRAKPUR'])]

print(df['ship-state'].nunique())

37

In [16]:
print(df['Amount'].describe())
print(df['Amount'].isna().sum())

count    121179.000000
mean        648.562130
std         281.212752
min           0.000000
25%         449.000000
50%         605.000000
75%         788.000000
max        5584.000000
Name: Amount, dtype: float64
7794

In [17]:
print(df[df['Amount'].isna()]['Status'].value_counts())

Status
Cancelled                       7565
Shipped                          208
Shipped - Delivered to Buyer       8
Shipping                           8
Shipped - Returned to Seller       3
Pending                            2
Name: count, dtype: int64

In [18]:
df = df.dropna(subset=['Amount'])
print(df.shape)

(121179, 23)

In [19]:
df['Date']=pd.to_datetime(df['Date'],errors='coerce')

C:\Users\Win -11\AppData\Local\Temp\ipykernel_25640\138852243.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Date']=pd.to_datetime(df['Date'],errors='coerce')

In [20]:
df.isnull().sum()

index                     0
Order ID                  0
Date                      0
Status                    0
Fulfilment                0
Sales Channel             0
ship-service-level        0
Style                     0
SKU                       0
Category                  0
Size                      0
ASIN                      0
Courier Status         5136
Qty                       0
currency                  0
Amount                    0
ship-city                31
ship-state               31
ship-postal-code         31
ship-country             31
promotion-ids         41698
B2B                       0
fulfilled-by          83639
dtype: int64

In [21]:
df = df.dropna(subset=['ship-city', 'ship-state', 'ship-postal-code', 'ship-country'])
print(df.shape)

(121148, 23)

In [22]:
print(df['Amount'].sum())

78573439.30000001

In [23]:
print(df['Order ID'].nunique())   # Total Orders (unique, not row count)
print(df['Qty'].sum())

113003
116453

In [24]:
total_ren=df['Amount'].sum()
AOV=total_ren/113003
print(AOV)

695.3217109280286

In [25]:
group1=df.groupby('Category')['Amount'].sum()
print(group1.sort_values(ascending=False))

Category
Set              39195176.03
kurta            21290970.70
Western Dress    11215337.69
Top               5346812.30
Ethnic Dress       791217.66
Blouse             458408.18
Bottom             150667.98
Saree              123933.76
Dupatta               915.00
Name: Amount, dtype: float64

In [26]:
group2 = df.groupby('Category')['Qty'].sum()
print(group2.sort_values(ascending=False))

Category
Set              45214
kurta            44955
Western Dress    13938
Top               9897
Ethnic Dress      1053
Blouse             844
Bottom             397
Saree              152
Dupatta              3
Name: Qty, dtype: int64

In [27]:
group2 = df.groupby('Category')['Qty'].sum()
print(group2.sort_values(ascending=False))

Category
Set              45214
kurta            44955
Western Dress    13938
Top               9897
Ethnic Dress      1053
Blouse             844
Bottom             397
Saree              152
Dupatta              3
Name: Qty, dtype: int64

In [28]:
cancelled = df[df['Status'] == 'Cancelled'].shape[0]
total = df.shape[0]
cancellation_rate = (cancelled / total) * 100
print(f"Cancellation Rate: {cancellation_rate:.2f}%")

Cancellation Rate: 8.88%

In [29]:
top_states = df.groupby('ship-state')['Amount'].sum().sort_values(ascending=False)
print(top_states.head(5))

ship-state
MAHARASHTRA      13335534.14
KARNATAKA        10481114.37
TELANGANA         6916615.65
UTTAR PRADESH     6816642.08
TAMIL NADU        6515650.11
Name: Amount, dtype: float64

In [30]:
df.to_csv('cleaned_amazon_sales.csv', index=False)

In [31]:
pip install pyodbc

Collecting pyodbc
  Downloading pyodbc-5.3.0-cp313-cp313-win_amd64.whl.metadata (2.8 kB)
Downloading pyodbc-5.3.0-cp313-cp313-win_amd64.whl (70 kB)
Installing collected packages: pyodbc
Successfully installed pyodbc-5.3.0
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [33]:
import pyodbc

conn = pyodbc.connect(
    'DRIVER={ODBC Driver 17 for SQL Server};'
    'SERVER=.;'
    'DATABASE=ecommerce_dashboard_v2;'
    'Trusted_Connection=yes;'
)

cursor = conn.cursor()
print("Connected successfully!")

Connected successfully!

In [34]:
products_df = df[['SKU', 'Style', 'Category', 'Size', 'ASIN']].drop_duplicates(subset=['SKU'])
print(products_df.shape)

(7157, 5)

In [35]:
for index, row in products_df.iterrows():
    cursor.execute(
        "INSERT INTO products (sku, style, category, size, asin) VALUES (?, ?, ?, ?, ?)",
        row['SKU'], row['Style'], row['Category'], row['Size'], row['ASIN']
    )

conn.commit()
print("Products inserted successfully!")

Products inserted successfully!

In [36]:
orders_df = df[['Order ID', 'Date', 'Status', 'Fulfilment', 'ship-city', 'ship-state', 'ship-postal-code', 'B2B']].drop_duplicates(subset=['Order ID'])
print(orders_df.shape)

(113003, 8)

In [37]:
for index, row in orders_df.iterrows():
    cursor.execute(
        "INSERT INTO orders (order_id, order_date, status_, fulfilment, ship_city, ship_state, ship_postal_code, b2b) VALUES (?, ?, ?, ?, ?, ?, ?, ?)",
        row['Order ID'], row['Date'], row['Status'], row['Fulfilment'], row['ship-city'], row['ship-state'], row['ship-postal-code'], row['B2B']
    )

conn.commit()
print("Orders inserted successfully!")

Orders inserted successfully!

In [38]:
order_items_df = df[['Order ID', 'SKU', 'Qty', 'Amount']]
print(order_items_df.shape)

(121148, 4)

In [39]:
for index, row in order_items_df.iterrows():
    cursor.execute(
        "INSERT INTO order_items (order_id, sku, qty, amount) VALUES (?, ?, ?, ?)",
        row['Order ID'], row['SKU'], row['Qty'], row['Amount']
    )

conn.commit()
print("Order items inserted successfully!")

Order items inserted successfully!

In [40]:
pip install flask

Collecting flaskNote: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip
Error reading stdout: timed out